<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="base_width" value="0.4" />
  <xacro:property name="base_length" value="0.6" />
  <xacro:property name="base_height" value="0.15" />
  <xacro:property name="polelen" value="0.7" />
  <xacro:property name="wheeldiam" value="0.3" />
  <xacro:property name="casterdiam" value="${(wheeldiam - base_height)/2}" />
  <xacro:property name="wheel_separation" value="${base_width + 0.1}" />

  <xacro:include filename="$(find my_robot)/urdf/materials.xacro" />

  <xacro:include filename="$(find my_robot)/urdf/inertials.xacro" />

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <xacro:box_inertial m="15" l="${base_length}" w="${base_width}" h="${base_height}"/>
  </link>

  <xacro:macro name="wheel" params="prefix reflect">

    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheeldiam/2}" length="0.1"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheeldiam/2}" length="0.1"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial m="0.8" r="${wheeldiam/2}" l="0.1"/>
    </link>
    <joint name="${prefix}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${(base_length - wheeldiam)/2} ${reflect*(base_width/2 + 0.05)} 0" rpy="0 0 0"/>
    </joint>

    <!-- This block provides the simulator (Gazebo) with information on a few additional
    physical properties. See http://gazebosim.org/tutorials/?tut=ros_urdf for more-->
    <gazebo reference="${prefix}_wheel">
      <mu1 value="2.0"/>
      <mu2 value="1.0"/>
      <kp value="10000000.0" />
      <kd value="1.0" />
      <material>Gazebo/Black</material>
    </gazebo>

    <!-- This block connects the wheel joint to an actuator (motor), which informs both
    simulation and visualization of the robot -->
    <!--transmission name="${prefix}_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="${prefix}_wheel_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="${prefix}_wheel_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
    </transmission-->

  </xacro:macro>

  <xacro:macro name="caster" params="prefix reflect">

    <link name="${prefix}_caster">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <sphere radius="${casterdiam/2}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <sphere radius="${casterdiam/2}"/>
        </geometry>
      </collision>
      <xacro:sphere_inertial m="0.5" r="${casterdiam/2}"/>
    </link>
    <joint name="${prefix}_caster_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="${prefix}_caster"/>
      <origin xyz="${-1*(base_length/2 - casterdiam/2)} ${reflect*(base_width/2 - casterdiam/2)} ${-((base_height+casterdiam)/2)}" rpy="0 0 0"/>
    </joint>

    <!-- This block provides the simulator (Gazebo) with information on a few additional
    physical properties. See http://gazebosim.org/tutorials/?tut=ros_urdf for more-->
    <gazebo reference="${prefix}_caster">
      <mu1 value="0.2"/>
      <mu2 value="0.1"/>
      <kp value="10000000.0" />
      <kd value="1.0" />
      <material>Gazebo/Black</material>
    </gazebo>

  </xacro:macro>

  <xacro:wheel prefix="right" reflect="-1"/>
  <xacro:wheel prefix="left" reflect="1"/>

  <xacro:caster prefix="right" reflect="-1"/>
  <xacro:caster prefix="left" reflect="1"/>

  <link name="pole">
    <visual>
      <geometry>
        <box size="0.05 0.05 ${polelen}"/>
      </geometry>
      <material name="white"/>
      <origin xyz="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 ${polelen}"/>
      </geometry>
    </collision>
    <xacro:box_inertial m="1.5" l="0.05" w="0.05" h="${polelen}"/>
  </link>

  <joint name="tobase" type="fixed">
    <parent link="base_link"/>
    <child link="pole"/>
    <origin xyz="${-0.25*base_length} 0 ${(base_height+polelen)/2}"/>
  </joint>

  <link name="screen">
    <visual>
      <geometry>
        <box size="0.02 0.08 0.1"/>
      </geometry>
      <material name="red"/>
      <origin xyz="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.02 0.08 0.1"/>
      </geometry>
    </collision>
    <xacro:box_inertial m="0.75" l="0.02" w="0.08" h="0.1"/>
  </link>

  <joint name="topole" type="fixed">
    <parent link="pole"/>
    <child link="screen"/>
    <origin xyz="0.035 0 ${0.4*polelen}"/>
  </joint>

  <!-- Hokuyo Laser -->
  <link name="hokuyo_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://my_robot/meshes/hokuyo.dae"/>
      </geometry>
    </visual>
    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="hokuyo_joint" type="fixed">
    <parent link="base_link"/>
    <child link="hokuyo_link"/>
    <axis xyz="0 1 0" />
    <origin xyz="${0.05 + base_length/2} 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Depth Camera: Kinect-->
  <link name="kinect_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.073000 0.276000 0.072000"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://my_robot/meshes/kinect.dae"/>
      </geometry>
    </visual>
    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="kinect_joint" type="fixed">
    <parent link="pole"/>
    <child link="kinect_link"/>
    <axis xyz="0 1 0" />
    <origin xyz="0.036 0 ${0.056 + polelen/2}" rpy="0 0 0"/>
  </joint>

  <!-- Gazebo -->
  <xacro:include filename="$(find my_robot)/urdf/robot.gazebo" />

</robot>